version: '3'
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: senzing-zookeeper
    ports:
      - '2181:2181'
    environment:
#     See https://github.com/bitnami/bitnami-docker-zookeeper#configuration
      ALLOW_ANONYMOUS_LOGIN: "yes"
    restart: always
    networks:
      - backend

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: senzing-kafka
    ports:
      - '9092:9092'
    environment:
#     See https://github.com/bitnami/bitnami-docker-kafka#configuration
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_NUM_PARTITIONS: 6
    depends_on:
      - zookeeper
    restart: always
    networks:
      - backend

  mockdata:
    image: senzing/mock-data-generator
    container_name: senzing-mock-data-generator
    environment:
#     See https://github.com/Senzing/docker-mock-data-generator#configuration
      SENZING_SUBCOMMAND: url-to-kafka
      SENZING_KAFKA_BOOTSTRAP_SERVER: senzing-kafka:9092
      SENZING_KAFKA_TOPIC: "senzing-kafka-topic"
      SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
      SENZING_RECORD_MAX: 9000
      SENZING_RECORD_MONITOR: 100
      SENZING_RECORDS_PER_SECOND: 10
    networks:
      - backend
    depends_on:
      - kafka
    restart: on-failure

  loader:
    image: senzing/stream-loader
    container_name: senzing-stream-loader-1
    environment:
#     See https://github.com/Senzing/stream-loader#configuration
      SENZING_SUBCOMMAND: kafka
      SENZING_DATA_SOURCE: PEOPLE
      SENZING_ENTITY_TYPE: PEOPLE
      SENZING_KAFKA_BOOTSTRAP_SERVER: senzing-kafka:9092
      SENZING_KAFKA_TOPIC: "senzing-kafka-topic"
      LC_CTYPE: en_US.utf8
    networks:
      - backend
    volumes:
      - ${SENZING_DIR:-/opt/senzing}:/opt/senzing
    restart: on-failure

  rest:
    image: senzing/rest-api-server-java
    container_name: senzing-rest-api-server
    ports:
      - '8888:8080'      
    networks:
      - backend
    volumes:
      - ${SENZING_DIR:-/opt/senzing}:/opt/senzing
    restart: always


networks:
  backend:
